# Generated by Django 5.0.6 on 2024-06-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=40, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripcion')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardinesVecinosApp.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
