# Generated by Django 5.0.6 on 2024-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinesVecinosApp', '0002_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(default=0, max_length=5, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
