# Generated by Django 5.0.6 on 2024-06-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinesVecinosApp', '0003_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_boleta',
            old_name='id_boleta',
            new_name='idBoleta',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default=1000, max_length=8, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
