# Generated by Django 5.0.6 on 2024-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinesVecinosApp', '0004_rename_id_boleta_detalle_boleta_idboleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
    ]
